# Requirements
# - PHP 8.2
# - NGINX
# - MariaDB 11.1
# - phpMyAdmin
# - MailDev

#########################
## FIX THESE           ##
## ------------------- ##
## * db_connect vals   ##
## * email vals        ##
#########################

volumes:
  db_data:

services:
  nginx:
    restart: unless-stopped
    build:
      context: ./nginx
      dockerfile: Dockerfile
      network: host
    depends_on:
      php:
        condition: service_started
      phpmyadmin:
        condition: service_started
      email:
        condition: service_started
    ports:
      - 80:80
    volumes:
      - ./Project:/var/www/html
    links:
      - php
      - phpmyadmin
      - db
      - email
  php:
    restart: unless-stopped
    build:
      context: ./phpfpm
      dockerfile: Dockerfile
      #network: host
    expose:
      - 9000
    volumes:
      - ./Project:/var/www/html
    depends_on:
      db:
        condition: service_started
    links:
      - db
      - email
  phpmyadmin:
    restart: unless-stopped
    image: phpmyadmin:5.2
    depends_on:
      db:
        condition: service_started
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_ABSOLUTE_URI: "http://localhost/phpMyAdmin"
  db:
    restart: unless-stopped
    image: mariadb:11.1
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: test1234
  email:
    restart: unless-stopped
    image: maildev/maildev:2.2.1
    ports:
      - 1080:1080
      - 1025:1025
