# Requirements (2025)
# - PHP 8.2
# - NGINX
# - MariaDB 11.1
# - phpMyAdmin
# - MailDev

volumes:
  # MariaDB volume
  db_data:
  # Note: web server volume is mounted to the host machine at /home/skills/website

services:
  # NGINX frontend for competitor sites
  web:
    restart: unless-stopped
    build:
      context: ./nginx
      dockerfile: Dockerfile
      network: host
    depends_on:
      php:
        condition: service_started
      phpmyadmin:
        condition: service_started
      email:
        condition: service_started
    ports:
      - 80:80
    volumes:
      - /home/skills/website:/var/www/html
    links:
      - php
      - phpmyadmin
      - db
      - email
  # PHP-FPM engine for running sites
  php:
    restart: unless-stopped
    build:
      context: ./phpfpm
      dockerfile: Dockerfile
    expose:
      - 9000
    volumes:
      - /home/skills/website:/var/www/html
    depends_on:
      db:
        condition: service_started
    links:
      - db
      - email
  # Database access tooling
  phpmyadmin:
    restart: unless-stopped
    image: phpmyadmin:5.2
    depends_on:
      db:
        condition: service_started
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_ABSOLUTE_URI: "http://192.168.101.51/phpMyAdmin"
  # MariaDB instance for sites
  db:
    restart: unless-stopped
    image: mariadb:11.1
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: CHANGEME
  # MailDev instance for site usage
  email:
    restart: unless-stopped
    image: maildev/maildev:2.2.1
    ports:
      - 1080:1080
      - 1025:1025
